name = "rdp-telegram-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

# Secrets di-set via CLI:
#   wrangler secret put TELEGRAM_BOT_TOKEN
#   wrangler secret put TELEGRAM_CHAT_ID
#   wrangler secret put GH_PAT_TOKEN
#   wrangler secret put GH_REPO
