name = "rdp-telegram-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

# Secrets di-set via CLI:
#   wrangler secret put BOT_TOKEN
#   wrangler secret put CHAT_ID
#   wrangler secret put GH_PAT_TOKEN
#   wrangler secret put GH_REPO
#   wrangler secret put WEBHOOK_SECRET
